services:
  db:
    image: postgres:16-alpine
    container_name: lumina-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lumina_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
        - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
        - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
        - RESEND_API_KEY=${RESEND_API_KEY}
    container_name: lumina-app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/lumina_db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - NEXT_PUBLIC_MIDTRANS_CLIENT_KEY=${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
      - MIDTRANS_IS_PRODUCTION=${MIDTRANS_IS_PRODUCTION}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
      - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}

volumes:
  postgres_data:
