import { Course } from "./types";

export const DUMMY_COURSES: Course[] = [
  {
    id: 1,
    title: "React Fundamentals for Beginners",
    category: "Frontend",
    instructor: "Andi Pratama",
    students: 284,
    lessons: 24,
    duration: "12h 30m",
    rating: 4.8,
    isFree: false,
    status: "published",
    thumbnail:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop",
    color: "from-blue-500 to-cyan-500",
    updatedAt: "2 hari lalu",
  },
  {
    id: 2,
    title: "UI/UX Design Masterclass",
    category: "Design",
    instructor: "Siti Rahma",
    students: 196,
    lessons: 32,
    duration: "18h 45m",
    rating: 4.9,
    isFree: false,
    status: "published",
    thumbnail:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2000&auto=format&fit=crop",
    color: "from-violet-500 to-pink-500",
    updatedAt: "5 hari lalu",
  },
  {
    id: 3,
    title: "Node.js Advanced: REST API & Microservices",
    category: "Backend",
    instructor: "Budi Santoso",
    students: 143,
    lessons: 41,
    duration: "22h 00m",
    rating: 4.7,
    isFree: false,
    status: "published",
    thumbnail:
      "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=2070&auto=format&fit=crop",
    color: "from-emerald-500 to-teal-500",
    updatedAt: "1 minggu lalu",
  },
  {
    id: 4,
    title: "Python for Data Science",
    category: "Data Science",
    instructor: "Dewi Lestari",
    students: 312,
    lessons: 36,
    duration: "20h 15m",
    rating: 4.6,
    isFree: true,
    status: "draft",
    thumbnail:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    color: "from-amber-500 to-orange-500",
    updatedAt: "3 hari lalu",
  },
  {
    id: 5,
    title: "Flutter Mobile App Development",
    category: "Mobile",
    instructor: "Rizky Hakim",
    students: 89,
    lessons: 28,
    duration: "15h 20m",
    rating: 4.5,
    isFree: true,
    status: "published",
    thumbnail:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop",
    color: "from-sky-500 to-blue-600",
    updatedAt: "4 hari lalu",
  },
  {
    id: 6,
    title: "Digital Marketing & Social Media Strategy",
    category: "Marketing",
    instructor: "Maya Sari",
    students: 0,
    lessons: 18,
    duration: "9h 00m",
    rating: 0,
    isFree: false,
    status: "draft",
    thumbnail:
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=2074&auto=format&fit=crop",
    color: "from-rose-500 to-red-500",
    updatedAt: "Hari ini",
  },
];
